### ISSUE TITLE
DataTransporter crashes when using FetchXML Filter

### ISSUE THREAD

**Issue by rowdy146** [bcolpaert/Colso.Xrm.DataTransporter#11]
Hello Developers,
can´t find any documentation on how to properly work with xml filters.

This is what I tried (validated within FetchXMLBuilder) which always ends up in crashing the plugin:

![image](https://user-images.githubusercontent.com/30408558/28522413-3956f256-7078-11e7-8a23-384da78a6226.png)

This is the result :(
[DataTransporterError.txt](https://github.com/bcolpaert/Colso.Xrm.DataTransporter/files/1169726/DataTransporterError.txt)

Using it without filter is a pleasure and much smarter than other middlewares :)
Any help would be greatly appreciated.
BR, Oliver

**Comment by bcolpaert** [comment]
Hi Oliver, 

You can only include the <filter> tag in the text field, not the entire fetch xml. 

Because of this, it is not supported to create a filter with a linked entity like in your example. 

I will note this as an improvement which I can include in future releases.

BR, 
Bram

**Comment by rowdy146** [comment]
Hi Bram,

thanks for your quick response but what do you mean with "you can only include the tag in the text field"?

I also tried to filter just like this (without linked entity) and the plugin crashes: 
![image](https://user-images.githubusercontent.com/30408558/28523719-f48e10c2-707d-11e7-84f7-db129ea2e757.png)

Regards, Oliver

**Comment by LastExile1** [comment]
Do you mean the filter tag element in the fetch xml?
````
<filter type="and">
      <condition attribute="modifiedby" operator="eq" uiname="Some User" uitype="systemuser" value="{245erF37-1DE6-E111-8E3A-1ff1DEE8Ddo6}" />
    </filter>
````

**Comment by bcolpaert** [comment]
Yes indeed, you can only include the <filter> element, just like @LastExile1  described.

In the case of @rowdy146 this means:

`<filter type="and">
      <condition attribute="pager" operator="begins-with" value="9" />
      <condition attribute="statecode" operator="eq" value="0" />
    </filter>`

**Comment by rowdy146** [comment]
In this case I´d suggest do change "help" text within filter function, as this was at least leading me to expect that also more complex fetch strings can be used..

![image](https://user-images.githubusercontent.com/30408558/28560671-f2cd1dc0-711b-11e7-8639-058cb3360602.png)

I confirm that working with `<filter>` tag & "flat" entity filters work like desired:
`<filter type="and">
      <condition attribute="statecode" operator="eq" value="0" />
      <condition attribute="pager" operator="like" value="9%" />
    </filter>`
