### ISSUE TITLE
Data transporter not working for perticular instance of my organization.

### ISSUE THREAD

**Issue by Dipesh0210** [bcolpaert/Colso.Xrm.DataTransporter#17]
Hi,

We've 3 D365 instances, DEV, UAT, and PROD. Your tool is very useful for migrating records from one CRM instance to another. Using your tool, in my case, I'm able to move the records from UAT to DEV and vice versa.

However, I'm not able move data from PROD to DEV or PROD to UAT. Not sure why? The tool is not able to get the recrods from PROD to insert them on any other CRM instances. On the other hand it is not displaying any errors as such. This is very urgnet request and we need to complete our work coming Monday EOD.

Any help against this problem would be much appreciated.

**Comment by bcolpaert** [comment]
Not sure why this is...Do you have any filters set up? Maybe the records already exist on the other CRM instances?

**Comment by Dipesh0210** [comment]
Thank you for the response. 
Is it possible for you to setup a Skype call, so that, I could demostrate the same to you over the call.

**Comment by bcolpaert** [comment]
yes offcourse. If you give me your email, I will send you an invite.

**Comment by Dipesh0210** [comment]
Thank you for the response.
My email address is "dipesh.patel@inkeysolutions.com"
