### ISSUE TITLE
FetchFilter

### ISSUE THREAD

**Issue by urban44** [bcolpaert/Colso.Xrm.DataTransporter#18]
Hello,

I want to use FetchFilter, but I do not know what is the right format of XML. I try to copy and paste fetch from advance find, but I get an error all the time.

my fetch (without first char < ) and error:
Thanks,
Stanislav Urban

fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false">
entity name="account">
 attribute name="name" />
 
 attribute name="accountid" />
order attribute="name" descending="false" />
filter type="and">
condition attribute="statuscode" operator="eq" value="1" />
/filter>
link-entity name="contact" from="contactid" to="primarycontactid" visible="false" link-type="outer" alias="a_8edc034c6cc2406aaa0274da494a1acd">
attribute name="emailaddress1" />
/link-entity>
/entity>
/fetch>

and error:

System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: Invalid Child Node, valid nodes are filter, order, link-entity, attribute, all-attributes, no-attrs. NodeName = fetch NodeXml = <fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false"><entity name="account"><attribute name="name" /><attribute name="address1_city" /><attribute name="primarycontactid" /><attribute name="telephone1" /><attribute name="accountid" /><order attribute="name" descending="false" /><filter type="and"><condition attribute="statuscode" operator="eq" value="1" /></filter><link-entity name="contact" from="contactid" to="primarycontactid" visible="false" link-type="outer" alias="a_8edc034c6cc2406aaa0274da494a1acd"><attribute name="emailaddress1" /></link-entity></entity></fetch> (Detail chyby se rovná Exception details: 
ErrorCode: 0x8004111C
Message: Invalid Child Node, valid nodes are filter, order, link-entity, attribute, all-attributes, no-attrs. NodeName = fetch NodeXml = <fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false"><entity name="account"><attribute name="name" /><attribute name="address1_city" /><attribute name="primarycontactid" /><attribute name="telephone1" /><attribute name="accountid" /><order attribute="name" descending="false" /><filter type="and"><condition attribute="statuscode" operator="eq" value="1" /></filter><link-entity name="contact" from="contactid" to="primarycontactid" visible="false" link-type="outer" alias="a_8edc034c6cc2406aaa0274da494a1acd"><attribute name="emailaddress1" /></link-entity></entity></fetch>
TimeStamp: 2018-03-20T10:06:16.1309305Z
--
Exception details: 
ErrorCode: 0x8004111C
Message: Invalid Child Node, valid nodes are filter, order, link-entity, attribute, all-attributes, no-attrs. NodeName = fetch NodeXml = <fetc...).

**Comment by bcolpaert** [comment]
Hi urban44.

Maybe this thread can help you: https://github.com/bcolpaert/Colso.Xrm.DataTransporter/issues/11

You can only include the filter element:
`<filter type="and"> <condition attribute="pager" operator="begins-with" value="9" /> <condition attribute="statecode" operator="eq" value="0" /> </filter>`

**Comment by urban44** [comment]
Hi bcolpaert,

thanks a lot.
