### ISSUE TITLE
Error after updated XrmToolBox

### ISSUE THREAD

**Issue by Hightower1** [bcolpaert/Colso.Xrm.DataTransporter#19]
After updating to version 1.2018.3.21 this evening the Data Transporter tool will not connect. This has been a very valuable tool and i thank you for providing it. The error I'm receiving is listed below. It happens regardless of the organization i connect to. 

An error occured when trying to display this plugin: Unable to case object of type 'Colso.DataTransporter.DataTransporter' to type 'XrmToolBox.Extensibility.PluginControlBase'.

**Comment by CommonDialog** [comment]
I am getting the same error.

**Comment by bcolpaert** [comment]
A new version 1.2018.3.2 is published which is compatible with the latest version of xrmtoolbox.
Bram

**Comment by Hightower1** [comment]
Does it take some time to show the newest version? I am still showing 1.2018.3.1
![image](https://user-images.githubusercontent.com/37645475/37773075-981b0864-2daa-11e8-95ab-0ab38f19e7b0.png)

**Comment by chrolivier** [comment]
I manually downloaded and installed 1.2018.3.1 from nuget.org.
Still getting the same error.

**Comment by bcolpaert** [comment]
1.2018.3.1 is the old version. 
You need to download version 1.2018.3.3 (1.2018.3.2 contains the wrong dll version)

**Comment by chrolivier** [comment]
Aah, thanks for the reply.
BTW: Thank you for a great tool. It has been really useful. +1

**Comment by glosrob** [comment]
Getting an error with latest plugin and latest XRM Toolbox using Dynamics 365 online.

![image](https://user-images.githubusercontent.com/2010333/37833762-1058d186-2ea4-11e8-8f93-1a1c220a7814.png)

Plugin installs fine, errors appears on connecting to an organisation

**Comment by glosrob** [comment]
Where can we get the latest version? As others have said, plugin store is still serving 1.2018.3.1.

**Comment by bcolpaert** [comment]
I've contacted Tanguy why XrmToolbox is not showing the latest versions. In the mean time you can manually download it from nuget: https://www.nuget.org/packages/Colso.Xrm.DataTransporter

**Comment by bcolpaert** [comment]
The latest version should be available from within the plugin store.
