### ISSUE TITLE
some feature requests

### ISSUE THREAD

**Issue by bryce2071** [bcolpaert/Colso.Xrm.DataTransporter#2]
Hi, 
this is one of the greatest tools i know :-) 
your are phenomenal!

1) 
could there be a possibility to not handle all instances of an entity, f.e. by using a view oder custom xml code. 
Reason: we have 2 different account types saved in account-entity, but only want to create/update 1 of these 2 accounttypes to a target crm

2)
could it be possible to save the marked attributes (and if you could integreat views/xml als filter, save this too).
Reason: Easily use the same set of attributs by loading the definition/s.

THX, Great tool.
Gr.PeB

**Comment by bryce2071** [comment]
Hi, 
thx for the versionupdate .. i saw that Point 1 is included (filter).
Thx very much. Its working perfect.

Gr.PeB

**Comment by bcolpaert** [comment]
Hi Bryce, 

Thanks for the feedback!

I will try to include the saving of the marked attributes in the next release.

I have however no timespan of when it will be...

BR,
Bram

**Comment by bcolpaert** [comment]
Saving of checked attributes is included in release 1.2016.11.1
