### ISSUE TITLE
Change State

### ISSUE THREAD

**Issue by urban44** [bcolpaert/Colso.Xrm.DataTransporter#20]
Hello,

I tried to use Status in transport. But I get an error. My target CRM is online v9. 

I get this error message:
This message can not be used to set the state of SalesOrder to Fullfilled. In order to set state of SalesOrder, use the FullfillSalesOrder Request. Request message instead.

Thanks,
Stanislav

**Comment by bcolpaert** [comment]
Hi,
Changing state on opportunities, cases, salesorders, .... is not supported since this requires special requests as stated in the error message.
