### ISSUE TITLE
Error with Closed Opportunities

### ISSUE THREAD

**Issue by CryogenicPotato** [bcolpaert/Colso.Xrm.DataTransporter#23]
Transporting a Closed Opportunity (Won or Lost) record properly creates it on the target Organization but fails to change its status with the following error:

> "This message can not be used to set the state of opportunity to Lost. In order to set the state of opportunity to Lost, use the LostOpportunityRequest message instead."

This is currently happening on Dynamics CRM On-Premise 2016 Update 1 (ver. 8.1.0.359).

**Comment by bcolpaert** [comment]
Hi, 
Changing state on opportunities, cases, salesorders, .... is not supported since this requires special requests as stated in the error message.

**Comment by bcolpaert** [comment]
Duplicate issue  #20
