### ISSUE TITLE
Error on opening with newest XRMtoolbox v1.2018.3.21

### ISSUE THREAD

**Issue by fpro123** [bcolpaert/Colso.Xrm.DataTransporter#24]
Hi, I'm getting an error on opening in the newest XRMtoolbox version: 

An error occured when trying to display this plugin: An object of type "Colso.DataTransport.DataTransporter" could not be converted to "XrmToolBox.Extensibility.PluginControlBase"

**Comment by fpro123** [comment]
Seems to work after a full uninstall and reinstall of XRMtoolbox.
Thanks for a great product!

**Comment by bcolpaert** [comment]
Glad you got it working :)
