### ISSUE TITLE
Possiblity to transfer entities with owner via lookup

### ISSUE THREAD

**Issue by duck-o-saurus** [bcolpaert/Colso.Xrm.DataTransporter#26]
Hello,

right now, when you are transferring an entity from a source to a target the data-field for the owner is filled via the associated ownerid (which must be linked in some kind to the systemuserid, if i am not mistaken).

This is in some way problematic, since in each Dynamics365(@cloud)-instance the user (and therefore it's systemuserid) are automatically generated, when a Office365-user gets a Dynamics365-license (and the correct group-membership) and therefore access to the instance.
In this case one is not able to transfer the systemuserid from one Dynamics365-cloud-instance to another. And therefore, you are not able to transfer the data-field owner of an entity.

For this case it would be very convenient if one can change the transfer-type from ownerid to owner-name-lookup. Actually, this is the default behavior of Dynamics365, if you import such data via the onboard-import-tools.

Best greetings :-)

**Comment by duck-o-saurus** [comment]
Hi bcolpaert,
this sounds like a possible solution for my problem. As soon as your new version is released, i will enjoy to try this out :-)

**Comment by duck-o-saurus** [comment]
Hi bcolpaert,
i ran in a similar issue to the one descripted before with the users. This time it's about the product-catalogue.
For importing a product (with it's productid) you need an uomschedule (with it's uomscheduleid) and an uom (with it's uomid) (inside the product-entity it's called defaultuomscheduleid and defaultuomid).
You run into trouble, when you use the uomschedule's primary uom for a product. This is, because you can't import the (primary) uom, because a new (regular) uom needs a primary uom. And to get a primary uom, you need to import a uomschedule first. But during an uomschedule-import a primary uom is automatically created (with the given import-parameters, but with a new uomid).
So also in this case a lookup against the name, rather than against the uid would be useful.

So maybe as a general enhancement for a future release, it's maybe very useful to choose which kind of lookup should be used for an import.

But maybe for that i need to change the topic of this issue or file a new one?

**Comment by duck-o-saurus** [comment]
Hey bcolpaert,
i would like to help to fix this issue by contributing some code.
If you like, you can contact me at duck.o.saurus.for.github@gmail.com
Best greetings

**Comment by bcolpaert** [comment]
Hi duck-o-saurus, 
Version 1.2018.7.1 is released which includes the mapping of system users.
BR

**Comment by duck-o-saurus** [comment]
Hey bcolpaert,
sorry for the late response. I was on vacation.

I updated XRMToolBox to v.1.2018.7.27 and Data Transporter to v.1.2018.7.1 and tried to migrate the owner-field, which does not succeed:

First try was to select the field "ownerid", which gives me the same error as before.
Second try was to unselect the field "ownerid" (because Auto-Mapping "System User Entity References" is on), but in this case the "ownerid" wasn't migrated as well.
Could you give me a hint, how this new feature works? Do i need to migrate some other data first?

Best greetings

**Comment by bcolpaert** [comment]
Hi duck-o-saurus, 

I could indeed reproduce the issue and there was a bug in the adding of the users.
This should be fixed in v1.2018.8.1 which is just release!

BR, 
Bram

**Comment by duck-o-saurus** [comment]
Hey Bram,
in my first tests the solution seems to work.
Thanks for this perfect time-saver :-)
