### ISSUE TITLE
ValidForRead properties not shown.

### ISSUE THREAD

**Issue by LBrisingamen** [bcolpaert/Colso.Xrm.DataTransporter#3]
Columns with the ValidForRead=='False' are selected by default and this is causing an error message.  It would be nice to remove the selection of them by default and possibly to show which ones they are similar to changes made for 1.2016.10.2.

**Comment by bcolpaert** [comment]
I see the problem. I will exclude the attributes which are not valid for read in the next release

**Comment by bcolpaert** [comment]
Issue is solved in release 1.2016.11.1
