### ISSUE TITLE
Settings file placed on desktop

### ISSUE THREAD

**Issue by rappen** [bcolpaert/Colso.Xrm.DataTransporter#5]
When starting XTB version 1.2017.2.13 a file ``Colso.DataTransporter.Settings.xml`` is created on my desktop.
It just contains this:
```
<?xml version="1.0"?>
<Settings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" />
```

Data Transporter tool is installed on my XTB, but it is hidden. Still creates this file.

**Comment by MscrmTools** [comment]
@bcolpaert you should use the SettingsManager class to store/load your settings

See : https://github.com/MscrmTools/XrmToolBox/blob/master/Plugins/MsCrmTools.SampleTool/SampleTool.cs#L32

**Comment by bcolpaert** [comment]
Thanks for the info!

I will include this in my next release.

**Comment by bcolpaert** [comment]
New release is available!
