### ISSUE TITLE
Transfer fails for Phone Calls

### ISSUE THREAD

**Issue by seang96** [bcolpaert/Colso.Xrm.DataTransporter#7]
After transferring the Phone Call entity, everyone of them fails due to system users GUID doesn't exist on the new instance of the CRM. I mapped the GUIDs in question as source with a target GUID representing the user in the new instance. The entity for these mappings I selected are user. 

The mapping have worked for accounts, contacts, notes, and tasks. I also have remapped the GUIDs in question after deleting the fields and the problem persists.

**Comment by seang96** [comment]
I looked at the issue some more and the ApplyMapping method does not find an attribute with the GUIDs that are an issue, but does find others and maps them when transferring Phone Calls. I am thinking that there is some kind of related entity that have these users that it is not applying the mapping for.

**Comment by bcolpaert** [comment]
Hi seang96, 

I believe the issue will be with ActivityParty entities. 

I'll have a look at this shortly and will include this in the next release.

**Comment by bcolpaert** [comment]
Thanks for the contribution!

I have published a new version including your changes for supporting ActivityParty in version 1.2017.3.1
