### ISSUE TITLE
Question -- are relationships kept intact?

### ISSUE THREAD

**Issue by DebSil** [bcolpaert/Colso.Xrm.DataTransporter#9]
Sorry to post here, but no Documentation.  Will this tool preserve relationships between data of multiple custom entities?

**Comment by bcolpaert** [comment]
Hi DebSil, 

Yes it can. 

If it are lookup fields (1-N , N-1), it is sufficient to include the lookup attributes in the transfer.

For many-to-many relationships, you can use the "Associations" tab to create the relationships.

BR, 
Bram
